# Generated by Django 6.0 on 2026-06-29 12:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique user identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the user profile was last updated')),
                ('email', models.EmailField(help_text="User's primary email address", max_length=254, unique=True)),
                ('password_hash', models.CharField(help_text='Hashed password', max_length=128)),
                ('first_name', models.CharField(blank=True, help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="User's last name", max_length=100)),
                ('username', models.CharField(blank=True, help_text='Unique username (optional)', max_length=50, null=True, unique=True)),
                ('profile_image_url', models.URLField(blank=True, help_text="URL to user's profile image")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user account is active')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
