# Generated by Django 6.0 on 2026-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='neon_auth_id',
            field=models.CharField(blank=True, help_text='Neon Auth user ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(default='neon-auth', help_text='Authentication provider (google, github, etc.)', max_length=50),
        ),
    ]
